#The text here is generated by AI. 

def welcome_message() -> None:
    print("========================================")
    print("      💰 BUDGET PLANNER API 💰       ")
    print("========================================")
    print("Welcome! Connecting to your database...")
    print("========================================\n")

def menu() -> None:
    print("\n--- 🏦 ACCOUNTS & WEALTH ---")
    print(" 1. View all accounts & balances")
    print(" 2. View a single account's balance")
    print(" 3. Add a new account")
    print(" 4. Edit an account's name")
    print(" 5. Delete an account")
    print(" 6. View your Net Worth")
    
    print("\n--- 📂 CATEGORIES ---")
    print(" 7. View all categories")
    print(" 8. Add a new category")
    print(" 9. Delete a category")
    
    print("\n--- 💸 TRANSACTIONS & TRANSFERS ---")
    print("10. Add an Income transaction")
    print("11. Add an Expense transaction")
    print("12. View all transactions")
    print("13. Delete a transaction")
    print("14. View all transfers")
    print("15. Add a new transfer")
    print("16. Delete a transfer")
    
    print("\n----------------------------------------")
    print(" 0. Exit Application")
    print("----------------------------------------")

def user_selection() -> int:
    while True:
        try:
            choice = int(input("Select an option (0-16): "))
            if 0 <= choice <= 16:
                return choice
            print("Invalid choice. Please select a number between 0 and 15.")
        except ValueError:
            print("Invalid input. Please enter a number.")